Model: "JEPA2Dv3"
teacher_forcing: true

out_channel: 64
patch_size: 5

r: 'diff'
sim_coeff: 25
std_coeff: 25
cov_coeff: 1
reg_coeff: 25
byol_coeff: 0
eps: 1e-4

batch_size: 512
epochs: 15
lr: 1e-5
weight_decay: 0
dropout: 0.1
noise: 0
