Model: "JEPA2D"
teacher_forcing: true

out_channel: 16
num_block: 2
num_resblock: 1

hidden_channel: 32

sim_coeff: 25
std_coeff: 25
cov_coeff: 10
reg_coeff: 50
eps: 1e-4

batch_size: 256
epochs: 100
lr: 1e-5
weight_decay: 5e-4
